name: CDIAghg
main: org.cdiadev.cdiaghg.Main
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/123654-dev/CDIAghg
author: 123654-dev
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
